version: '3.8'

services:
  web:
    build: .
    container_name: kavarna_u_pole
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    stdin_open: true
    tty: true
